### ISSUE TITLE
FAQs -  minor content edits

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#100]
1) On the FAQs page,  under "Getting Started" section, please change "Who qualifies as an under-represented minority?" to 
Who qualifies as an underrepresented minority?

2) Please change the first sentence of this answer from, "Reskill Americans' charter is to increase opportunities for traditionally underrepresented minorities in the tech industry" to:

Reskill Americans' charter is to increase access to careers in tech for historically underrepresented minorities.

3) In this same answer, please delete the last multiple choice option:  "Disabled (as defined by the Americans Disabilities Act)"

4) In the Program Details section, for the third question, "Can I catch up if I miss a live class"? please change the answer to:

There are no set classes; participants will work individually on assignments and then meet with the instructor and/or mentors at their convenience when they have questions and or need help.

**Comment by mckoss** [comment]
I don't think the answer to 4 is quite correct. There will be some live sessions.  The question is - what happens when they miss one?

I think the correct answer would tell participants that we record the live sessions and they will be able to watch the recording of any session they missed.

**Comment by mckoss** [comment]
All these changes have been made.

**Comment by ashlchap** [comment]
Hi - thanks for this. How about instead:
You will be able to watch the recording of any session that you miss, and you will have the option to meet with your instructor and/or mentors when you have questions and or need help.
