### ISSUE TITLE
News Page: new blog post

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#110]
Hi Tobi - I'd like to post this story below on the News page as the newest blog, with screenshots of the projects to go with it. I was thinking it could be like a carousel of photos for the screenshots with the story below the photos, but I defer to you on that. 
The link to the folder with the screenshots is at the bottom of this story: please post them in order of how they appear in the story, and by their number.  I will email you the link to this folder so that you can access it. (That's the only way I can give you permission)
Thank you and LMK what questions you have!)
Ashley

*********

(Headline  & story is below)

Showcasing Some Final Projects from Our 2021 Session 

At the end of our inaugural 2021 session, participants created final projects that reflected their newly-acquired skills as well as their incredible persistence, dedication and creativity.  Please scroll down to learn about a few of them. 

Live Look  
Team: Michael Bostick 
https://www.figma.com/file/HxsYe8XaKV7mtHlI2WxxoO/Design-Board?node-id=53%3A648  

Michael joined Reskill Americans with experience in the restaurant industry. His demo project, Live Look, allows users to view live surveillance footage of restaurants and other businesses to inform their decision-making better. The feature offers transparency on the things customers want to know, like how busy a restaurant is or how the kitchen operates. Michael developed Live Look to integrate into Yelp’s existing design and envisions that the feature can be seamlessly integrated into other apps as well. Michael’s experience with Reskill Americans allowed him to discover his ability to work on a team, conduct research, and problem solve. “Reskill really helped me figure out what I wanted to do,” said Michael. 

COVID Tracker 
Team: Lauren Smalls, Talisa Foster, Sharifa Nichols, Richard Jackson, Shelique Richardson 
 https://unruffled-kalam-99707e.netlify.app/ 

Lauren presented the COVID Tracker project on behalf of her team. Lauren currently works on a college campus and noticed an issue with COVID-related communications. Her team developed a COVID Tracker that would house all the information a student may need in one spot. The project included a real-time look at stats, along with details regarding vaccination availability and policies. Team members who worked on the COVID Tracker were flexible and resilient as they learned to coordinate within time zones worldwide. The team also expanded their skills when they unexpectedly had to play the role of backend developer and designer.  
 
More Knickknacks  
Team: Karl and Lorraine Boehringer 
https://kboeh.github.io/knickknacks/  

Karl and Lorraine are the husband-and-wife team behind More Knickknacks. The idea was inspired by Karl's mother, who wants to sell her collection of antiques after retirement. The project was a family affair: Karl and Lorraine learned how to communicate as colleagues, working together in a designer-developer relationship.  As a first-generation student, Lorraine said that she left the program with “confidence and enough work to build a portfolio.”  

Century Health  
Team: Jarla Kornegay, Christian Villaroel, Tasha Taylor, Micheleine Beaucejour 
https://medical-aids-fe-1.netlify.app/index.html  

Jarla Kornegay presented The Century Health App on behalf of her team. The app aims to find a way to grant quick access to medical information for patients. The team’s demo included a look at the patient portal and the physician’s portal. The final project included many features, such as a dynamic calendar, appointment submission, and a physician schedule. Jarla said that one of the biggest lessons she took away was “the need for persistence in finding a solution to a problem and for sometimes testing your own instincts even if you’re a beginner.” 

Here's the link to the folder with the screenshots: (see my email to you!)

https://netorgft7227627.sharepoint.com/sites/RSA2022/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FRSA2022%2FShared%20Documents%2FCommunications%2FWebsite%2F2021%20Site%20Redesign%20Copy%2Fcontent%2Fnews%2FDemo%20Day%20Project%20Screenshots&viewid=3d08b808%2D4651%2D465f%2D96ee%2D3ec26f38270d

**Comment by AlexMNet** [comment]
@ashlchap I don't have access to the folder. Mike mentioned changing the permissions in order for me to gain access?

**Comment by ashlchap** [comment]
Hi Alex -
I just sent the folder link to your email (it has been done that way) and gave you access that way, so please lmk if you could gain access.
Thanks!
Ashley

**Comment by AlexMNet** [comment]
@ashlchap Yes I have access now! Thank you!
