### ISSUE TITLE
News page: small content & design edit

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#111]
Hi Tobi,

Two small edits:

1) Since I asked you to post a story about the Demo Day projects, I'd like to change the headline of the existing demo day blog from 
'Final Demo Day Featuring A Few Projects from our Inaugural Cohort' to simply:
"Final Demo Day for 2021 Session"

2) Could you please change the photo for this story to a different one? I'd rather it feature a screenshot of one of our participants speaking, or one of the entire group from the Demo Day on Youtube. You can find that when you click on the story- it takes you to the youtube session. I know that this photo is much better, visually, but it is misleading as he's not a participant. 

Please lmk if you have questions. Thanks! Ashley

**Comment by ashlchap** [comment]
Hi Alex! I'm not sure if Mike has told you but we are hoping to launch the website tonight. These changes aren't critical to launch, but I'd love to get them up soon. Would it be possible to make these blog changes within the next 24 hours? There's another minor change needed and I'll assign the issue to you as well. Please LMK. Thanks, Ashley

**Comment by AlexMNet** [comment]
Hi @ashlchap ! I didn't know you guys were planning on deploying tonight. I just flew out of town this morning. I was going to try working with it a little bit tonight but since I'm traveling it might be best to reassign this so that it gets done in a timely manner. I do apologize for just letting you know. I return to California Friday evening and can start taking assignments again then.

**Comment by ashlchap** [comment]
Absolutely NO problem. We didn't give you any notice and I didn't know what your schedule is. If we have assignments on Friday (which I'm sure we will!) I'll send them to you. Thank you Alex!

**Comment by sylvercodez** [comment]
fixed @mckoss

**Comment by mckoss** [comment]
> Hi Tobi,
> 
> Two small edits:
> 
> 1. Since I asked you to post a story about the Demo Day projects, I'd like to change the headline of the existing demo day blog from
>    'Final Demo Day Featuring A Few Projects from our Inaugural Cohort' to simply:
>    "Final Demo Day for 2021 Session"
> 2. Could you please change the photo for this story to a different one? I'd rather it feature a screenshot of one of our participants speaking, or one of the entire group from the Demo Day on Youtube. You can find that when you click on the story- it takes you to the youtube session. I know that this photo is much better, visually, but it is misleading as he's not a participant.
> 
> Please lmk if you have questions. Thanks! Ashley

@ashlchap Are you aware that changing these images will also change the image shown in the partner page carousel?

**Comment by ashlchap** [comment]
Hi @sylvercodez per Mike's comments, please ignore item #2 above, we can keep the photo the same. However, please do change the headline to the new title, and pls post the new blog post. Thanks!
