### ISSUE TITLE
Partner page: replace a photo & correct typo

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#113]
Hi Tobi,

Can you please make two small corrections on the partner page? Under the words 'Thank you', are the Town Hall quotes. The last box featuring quotes is Rigetti Computing:

1) We need to change the photo, as it should be of Manrique, who said that quote (not Eric who is the shown) 
Can you please replace the photo with one of Manrique? Please try one of these photos for Manrique:  
- his linkedin: https://www.linkedin.com/in/manriquezuniga/
- OR grab a screenshot from the youtube session here: https://www.youtube.com/watch?v=CfwJ0AuxMk4&t=3377s
Manrique Zuniga, Rigetti Computing

2) In Manrique's quote, the "t" was missing in "projecs", please replace the entire quote with the corrected version below:
"You guys took on some really challenging projects ... you attacked real world problems and brought solutions that were relevant…it was eye opening to see how these apps were developed and thought out."

**Comment by sylvercodez** [comment]
fixed @mckoss

**Comment by ashlchap** [comment]
@sylvercodez I don't see the new correction yet, could you please confirm?
