### ISSUE TITLE
Content edits to Homepage & About Us pages: headline changes

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#119]
1) Please change the headline on the homepage from 
"Launch your career in tech: enroll in our free training program" to:

Increasing Access to Careers in Tech

2) Please change the headline on the About Us page from "Increasing Access to Careers in Tech" to:

Our Mission

**Comment by sylvercodez** [comment]
@ashlchap  should i fix this

**Comment by ashlchap** [comment]
That would be great if you can, in addition to any other content changes I've posted. Thanks Tobi!
