### ISSUE TITLE
Homepage: design + content changes

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#132]
***Note to Tobi/Alex: The following 3 changes below are temporary changes we'd like to make NOW, until we can open enrollment and post the enroll button. Mike requested they be based on the options flag that he implemented in the configuration file. So when we're ready to go live with enrollments all we have to do is change the setting of that flag and redeploy.  *****

CHANGES
1. Below the photo of Nia, (but above Learning Tracks) please create a new section and post in large font:
Do you share our mission to help underrepresented minorities get access to training so that they can build careers in tech?

2. Post a button right below that sentence that says "Partner with Us," and link it to the partner page. 
This section should be right above the "Learning Tracks" section 

3. At the bottom of the homepage, delete "Partner with Us" and the sentence "We are seeking partners in the tech industry that share our mission to help underrepresented minorities get access to training so they can build careers in technology." Please keep the Contact Us button the same in this spot.

**Comment by mckoss** [comment]
I'm going to finish up PR #146
