### ISSUE TITLE
News page: new photo for blog

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#137]
For the blog "Showcasing some final projects from our 2021 Session," it is hard to see what the small box says in the photo, so let's choose a different photo. Please replace the current photo with one of the following screenshots: (I defer to you on which looks better visually)

1) The photo in the folder (via link below) titled CenturyHealth3.jpeg 
OR
2)  the one saved as covidtrackerscreenshot2 (the photo says Covid Tracker across the top)

Link to folder is here: (Tobi I emailed you this so you should have access)
https://netorgft7227627.sharepoint.com/sites/RSA2022/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FRSA2022%2FShared%20Documents%2FCommunications%2FWebsite%2F2021%20Site%20Redesign%20Copy%2Fcontent%2Fnews%2FDemo%20Day%20Project%20Screenshots&viewid=3d08b808%2D4651%2D465f%2D96ee%2D3ec26f38270d

**Comment by mckoss** [comment]
I'll take a look at this.  I might not have had good examples for how to embed images in a blog post.
