### ISSUE TITLE
Summary Text in News page clipping 

### ISSUE THREAD

**Issue by AlexMNet** [reskillamericans/website#140]
Certain posts with text such as long URLs are clipping. Also some posts with not much text have huge spaces in between words.

**Comment by mckoss** [comment]
It's really a content error to have very little text in these posts and to have naked long URL's in them.

I'd be in favor of just editing the content to remove these anomolies.

**Comment by AlexMNet** [comment]
@mckoss that sounds like a a good way to go!

**Comment by AlexMNet** [comment]
@mckoss here is the PR for the margin! I believe the text align justify issue we are having will be fixed by editing the content as you mentioned? If not we can create that as a separate issue.
