### ISSUE TITLE
Glitches from Firefox mobile - to fix before launch if possible

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#150]
Please address all bugs from firefox: viewers are unable to see the following when on mobile using Firefox:
-the dropdown menu (of nav bar)
-the carousel on homepage

**Comment by mckoss** [comment]
What does that mean "unable to see" the dropdown menu.  Can you post a screen shot?

When I look on Firefox desktop, I see the dropdown menu is not blurred - so the text is hard to read.  Is that what you're talking about?

@ashlchap

**Comment by mckoss** [comment]
I can see Carousel on Firefox desktop.  What is happening on mobile???

@ashlchap

**Comment by mckoss** [comment]
Screenshot from FF (Windows)

![image](https://user-images.githubusercontent.com/82750/152072479-cad000e5-82c6-41c3-a8b8-73c8b471663a.png)

**Comment by ashlchap** [comment]
Apparently the glitches are only on mobile. I'll send you a screenshot amanda sent - she said the drop down menue didn't show up. Femi said he can only see Alex Gomez on the homepage  from Firefox mobile and not the carousel- he said this in the all hands message. this is the photo from Amanda here 
![image](https://user-images.githubusercontent.com/96091660/152072602-ef241b05-0845-408c-a0e3-ced25cba8bb5.png)

**Comment by AlexMNet** [comment]
@ashlchap I tested this on my phone and didn't have this issue. Quite odd. Do we know which phone and screen size she is using?

**Comment by ashlchap** [comment]
Hi @AlexMNet! oh, I'm so sorry, I meant to resolve this. Amanda later figured out she had something wrong with her phone but in the chaos of wrapping up changes, I totally forgot to resolve it here. Thank you for responding! I'll close it now.
