### ISSUE TITLE
All videos on website: tweak via youtube configuration

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#155]
At the end of the two Femi videos on our site, YouTube suggests other random YouTube videos to watch. Can we configure it so that it links to other videos on our RA YouTube channel instead, so that it aligns to our RA brand? (Femi seems to think there is a configuration for this when you embed a video on YouTube?) Below are the videos where we'd like to make this change:

1. About Us page: Femi video at the bottom 
2. Donate page: Femi video
3. (to come) Homepage: Raynell video (we hope to share this later tonight when we get it!)

**Comment by mckoss** [comment]
I looked for a setting like this and could not find one.

**Comment by ashlchap** [comment]
Ok that's fine. I will ask Femi where he got that idea. thanks

**Comment by mckoss** [comment]
I found it - add ?rel=0 to iframe url!
