### ISSUE TITLE
Testimonial Tweaks

### ISSUE THREAD

**Issue by mckoss** [reskillamericans/website#157]
Couple of design issues with the testimonial carousel.

- It's kind of large and out of proportion to the rest of the page design.  Maybe reduce the font sizes.
- The Next/Prev buttons are hard to see.  Increase the color contrast.

**Comment by mckoss** [comment]
- Picture looks odd centered vertically.  I think top aligned would look better in general. (top of image aligns with top HR over the quote).

**Comment by sylvercodez** [comment]
@ashlchap looking at this issue it is something I can do.. should I make a pr for this cc: @mckoss

**Comment by mckoss** [comment]
That would be great.  You can assign it to yourself.  It would be good to have her approve a new design before making a coffee change.
