### ISSUE TITLE
About Us page: rearranging a few team photos

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#158]
This is NOT a priority, but under Meet the Team, I think it looks very odd that Amanda is on a line by herself. Instead, can we put Femi and Mike on the top row (as co-founders) and the rest of the team is on the second row? 

So it would be:

Femi  & Mike (top row) 
Pam, Ashley, Juwon & Amanda (second row)

Please let me know if this would look ok

**Comment by mckoss** [comment]
Isn't this totally dependent on screen size?

**Comment by ashlchap** [comment]
@mckoss apologies - I see now and you are indeed correct! I will close this issue
