### ISSUE TITLE
Partner page: Caption needed under photo of Nia Bailey

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#168]
I just noticed that we need a caption under the Nia photo (at the computer) on the Partner Page. This should be similar to the caption on the Learn More page. Please write the below - in same font as the photo caption on the Learn More page:

Nia Bailey completed our 2021 program as a UI/UX designer.

Thanks!

**Comment by ashlchap** [comment]
Hi @AlexMNet  and @sylvercodez Tobi! Just tagging you both in case one of you could do this by tomorrow. Please LMK if you have any questions. Thanks!

**Comment by AlexMNet** [comment]
@ashlchap Sorry I have been away for the last several hours. I can take a look at that a little later tonight!

**Comment by sylvercodez** [comment]
@ashlchap I will do this thanks

**Comment by sylvercodez** [comment]
Fixed it awaiting merge

**Comment by AlexMNet** [comment]
@sylvercodez thank you for the heads up!
