### ISSUE TITLE
Replace video on homepage with this slightly edited version

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#173]
Hello. We would like to replace Raynell's video on the homepage with one that is 15 seconds shorter (so it's 2:45 not 3 min). (Thank you to Seyi and team!) We have uploaded it to youtube, link is below.

Could someone please use this in replacement, ensuring it's the same size as the current one on the homepage?

https://www.youtube.com/watch?v=V3vqrYyqFXo&feature=youtu.be

Please reach out with questions.
Thanks!

**Comment by sylvercodez** [comment]
Just seeing this I will fix this .. please if I can be tagged to issues like this I will be glad because I don't get notifications aside I'm tagged 

Thank you @ashlchap
