### ISSUE TITLE
News page: Small correction to top blog post

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#176]
Hello Tobi or Alex (tagging you both so whomever sees this first could please address it?): 

For the most recent Blog post titled "Showcasing Some Final Projects from our 2021 Session," under the Century Health story at the end, we need to make a correction to one of the names. Please replace Micheleine Beacejour with Michale Bailey (note the spelling). So the correct team list should read:

Team: Jarla Kornegay, Christian Villaroel, Tasha Taylor, Michale Bailey 

Thanks!

**Comment by AlexMNet** [comment]
@ashlchap fixed in this PR!

**Comment by sylvercodez** [comment]
Oh great thank you @AlexMNet
