### ISSUE TITLE
Homepage: Small addition to copy

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#196]
Under "Enrolling is Easy" please change the sentences below it to read: (I added LinkedIn plus a link to our video with Teddy here - : https://www.youtube.com/watch?v=iubjqvaqZHM&feature=youtu.be )

(NEW) 
Enrolling is Easy
No credit check, entrance exam, or prior knowledge/experience required. All you need is a computer with a web browser, and a LinkedIn profile. (Don't have a LinkedIn profile? ![image](https://user-images.githubusercontent.com/96091660/162548780-ef7abfbd-51c5-44a5-af70-102b6845c178.png) to get some topline tips)

**Comment by AlexMNet** [comment]
Hi @ashlchap ! Just wanted to let you know I will be able to get to these issues tomorrow!
