### ISSUE TITLE
Add Rigetti Consulting to "pull quote" section on Partner Page

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#41]
Quote is from Eric: 

You guys took on some really challenging projects… …you attacked real world problems and brought solutions that were relevant…it was eye opening to see how these apps were developed and thought out.”

Eric Amemiya, Talent 

Manrique Zuniga, Hardware Talent Acquisition 

Rigetti Computing  

You can find Eric's photo on his linkedin page: https://www.linkedin.com/in/ericamemiya/

**Comment by mckoss** [comment]
Partner pages quotes come from videos (this is in the Thank You section, right)?  Was this said in a video?  I'm not finding it.

**Comment by mckoss** [comment]
I found it - the final demo day video (12/7/21)

**Comment by mckoss** [comment]
There was not room for both of their titles to be displayed - I abbreviated as this:

![image](https://user-images.githubusercontent.com/82750/147851497-4fed054a-e7a8-48eb-81a0-df5ae7d1103b.png)

**Comment by ashlchap** [comment]
This looks good to me!
