### ISSUE TITLE
Add mailing list signups

### ISSUE THREAD

**Issue by mckoss** [reskillamericans/website#57]
Should we provide options for different lists?

- General/supporter
- Partner (companies)
- Volunteer
- Future participants (not yet applied)

**Comment by ashlchap** [comment]
Yes this is a good idea.  Is there anything you needed from me to do this? I see you have the content of the forms up there and I'll review those now

**Comment by ashlchap** [comment]
I've been thinking about this and it would probably be best to discuss this live so I understand the back end of how the lists are created, but here's my thoughts: 
We don't want to create a bunch of different newsletters.  The newsletter option at the bottom should stay general and be a generic monthly update we send to all audiences that covers everything from program updates (start dates, program updates - i.e. data on the program/phase updates, etc - participant news/people who've gotten jobs, demo days, etc). 

If we want people to enroll, they should only do that the enrollment form. If we want them to volunteer, they should only do that through the volunteer form. If we want people to partner with us, they contact us through the Partner button. 

We WILL have specialized communications to participants once they enroll with updates about the program, and we will have specialized volunteer communications to volunteers. (And specialized emails to donors once they donate.)

The monthly newsletter would be a generic update sent to donors/target donors, partners/target partners, advisory board, volunteers, participants, etc.

Let me know your thoughts. I may be missing something. We should discuss on our call tomorrow night.

**Comment by mckoss** [comment]
So, just one newsletter - for general news.

Add to mailchimp segment.

**Comment by mckoss** [comment]
![image](https://user-images.githubusercontent.com/82750/151922069-8be9d7c5-f1c8-40ed-aa87-f4957dfb9abf.png)
