### ISSUE TITLE
Add participant projects screenshots and story

### ISSUE THREAD

**Issue by mckoss** [reskillamericans/website#60]
For the blog?

[Michale Bailey Project Images](https://netorgft7227627.sharepoint.com/:f:/s/RSA2022/Ei39kaCD0nlKkJ64mId3hHABOVXJiCwaPPzITxH1dUHjNw?e=bXWIOG)

**Comment by ashlchap** [comment]
Do you mean post a story separate from the Demo Day blog and youtube video? I agree that we should show the projects and write a brief description, with photos of the images. I would suggest we combine it with the existing blog but we can't add more images there, right, as it ties to YouTube? Please clarify and in the meantime I'll write a summary sentence on each project.

**Comment by mckoss** [comment]
Yes - I mean a blog post using the project images provided.

**Comment by mckoss** [comment]
Blog posts can have as many images as we want - it's just the video downloads that are limited to their format (and even those could be made more extensive if we find a need).

**Comment by ashlchap** [comment]
FYI this is now a separate blog post/issue addressed to Alex
