### ISSUE TITLE
Volunteer Form: small edits/revisions, see my notes to you in parentheses

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#61]
(edited 2nd sentence below: added hyphen in seven-month training)
Thank you for your interest in volunteering with Reskill Americans. We are looking for volunteer mentors to meet regularly with our participants during the course of our seven-month training program.

(edit: rewrote first sentence below)
We seek volunteers that have technical expertise in product design and/or full stack web development. Whether you are an industry veteran, or someone who has just completed a boot camp yourself, we could use your help!

(edit: spelled out number in first sentence and rewrote second sentence)
We are asking for a minimum commitment of two hours per week, over a period of at least two months. During that time, you will be paired with participants learning a track that's aligned to your skillset. 

#7 (edit: Third sentence: remove the word 'twice'. Also, are you asking them to serve AS a TA? Or to support a TA? We should clarify which): 
Serve a primary TA for a group of 15 participants - weekly meetings.

#8 When would you be ready to start? 
(edits below: changed months and phase 0 to Intro phase. NOTE: I guessed on months so pls change accordingly)
February 2022 (Intro Phase ) March 2022 (Phase 1 Start) May 2022 (Phase 2 / Individual Projects)

**Comment by mckoss** [comment]
This page is a placeholder - will update when final form in place.
