### ISSUE TITLE
Enrollment Form - small edits

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#63]
Third bolded sentence on page:
(edit: deleted bootcamp. I didn't think we were using bootcamp, or at least we haven't yet so we should be consistent?)
-Reskill Americans - 2022  Enrollment Form

Next sentence (edit: changed applications to enrollment and hyphenated seven-month)
-We are accepting enrollment for participation in our seven-month software development training program.

#8 (edit: change belong to "self identify" and delete "in STEM workforce" as it sounds like they are already IN the field. Note: if you feel strongly about including STEM, then we should revise it to something like:..."I self identify as a historically underrepresented minority as defined by the STEM workforce.")
-I self-identify as a historically underrepresented minority 

#10 (edit: spell out 3rd)
-(you may change tracks up until the third week of the program).

**Comment by mckoss** [comment]
These are just placeholders - for the real forms.  Will do edits when converted.
