### ISSUE TITLE
New testimonial and photo: Raynell Carmichael

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#66]
NOTE: Suggested quote for post is below; full quote & photo are in links below. If quote is still too long let's cut the first 2 sentences

The best part about the program is the community. You meet like-minded individuals from all professional backgrounds who are kind and helpful. I never once felt like I couldn’t get through the program because of all the support that’s available. If you are looking to get into the industry, and learning the fundamentals that can set a strong foundation on your journey into tech, sign up right away. I entered the program knowing nothing, and left with a portfolio and knowledge that pointed me into the right direction. Two months after the program, I got a paid internship at a startup called Lucinetic. 

Raynell Carmichael
Los Angeles, CA

Full quote:
https://netorgft7227627.sharepoint.com/:w:/r/sites/RSA2022/_layouts/15/Doc.aspx?sourcedoc=%7BB1FDFFD1-8D3E-438F-882D-D1BDA83C0C4D%7D&file=Raynell%20Carmichael%20quote.docx&action=default&mobileredirect=true

photo: 
https://netorgft7227627.sharepoint.com/sites/RSA2022/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FRSA2022%2FShared%20Documents%2FCommunications%2FWebsite%2F2021%20Site%20Redesign%20Copy%2Fcontent%2Ftestimonials%2Fraynell%2Dcarmichael%2FRaynell%20Carmichael%2Ejpeg&parent=%2Fsites%2FRSA2022%2FShared%20Documents%2FCommunications%2FWebsite%2F2021%20Site%20Redesign%20Copy%2Fcontent%2Ftestimonials%2Fraynell%2Dcarmichael

**Comment by mckoss** [comment]
04da3fa6c6c853d7cf0798cb578bb34ec71d392c
