### ISSUE TITLE
New testimonial and photo: Alejandra Gomez

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#67]
NOTE: Suggested quote below, see link below that for folder with full quote and photo:

Many bootcamps are super expensive and require a full-day attendance. With the Reskill bootcamp, you learn at your own pace and at no cost! They truly care about your success. Reskill changed my life in less than a year: after completing the program, I got a job as a Junior Software Engineer Analyst at Wells Fargo! 

Alejandra Gomez
New York, NY

https://netorgft7227627.sharepoint.com/sites/RSA2022/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FRSA2022%2FShared%20Documents%2FCommunications%2FWebsite%2F2021%20Site%20Redesign%20Copy%2Fcontent%2Ftestimonials%2Falejandra%2Dgomez&viewid=3d08b808%2D4651%2D465f%2D96ee%2D3ec26f38270d

**Comment by mckoss** [comment]
04da3fa6c6c853d7cf0798cb578bb34ec71d392c
