### ISSUE TITLE
Edit to Our Program page

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#72]
Replace first sentence under headline at top of page (Over seven months, you will learn the fundamental concepts of software development through a range of formats: recorded and live video sessions, training modules, and online video conferences with your instructors and mentors (collectively requiring a minimum of 15 hours a week*) with: 

-Participants who complete our seven-month program will have applied their new skills to software development projects, worked on cross-functional teams and built a portfolio of work to show future employers. 

*Note to Mike: I'm moving this to the FAQs, see new FAQ edit

**Comment by mckoss** [comment]
By program page, I assume you mean "/learn-more" page.

**Comment by mckoss** [comment]
I wonder if we should more prominently link to our FAQ from this page?

**Comment by ashlchap** [comment]
Yes, I'm so sorry, I meant "Learn More" page, and yes, I think it we could do that, however, did you see the feedback about moving FAQs up to the Nav bar? People felt it should be easier to find. We could probably also include a sentence on the Learn More page.
