### ISSUE TITLE
Two Changes to FAQ page

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#73]
1) Please insert this Q&A question as one of the first in Program Details section: 

Q: What will be the teaching format? 
A: Over seven months, you will learn the fundamental concepts of software development through a range of formats: recorded and live video sessions, training modules, and online video conferences with your instructors and mentors (collectively requiring a minimum of 15 hours a week. 

2) In the Tracks section, under "Are there any software or hardware recommendations?" I inserted the second sentence (moved from homepage) below so please replace the whole answer with this:

A:  You can use any computer or laptop /desktop, Mac or Windows. A Windows or Macintosh laptop where you can install VS-Code will provide the best experience. In terms of RAM, we recommend the following for each track:

For full stack web development: Min. 4GB RAM
For product design UX/UI: Min. 4GB

**Comment by mckoss** [comment]
I'm adding to the (unanswered software part of that question):

All the software used will be free - either online or installed on your computer.
It is possible to do every part of this program using all online resources, so
you just need a computer with a web browser.

**Comment by ashlchap** [comment]
Great, thank you for catching that
