### ISSUE TITLE
Homepage: Join Our Next Session button

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#85]
Please replace the copy  "Join Our Next Session" on the button at top of page with the following:

Details Coming Soon! 

And please do not link the button to anything.

**Comment by mckoss** [comment]
So you want it to remain a button?  Why not remove it?

**Comment by ashlchap** [comment]
I think it helps build interest/momentum, as if the date could be imminently announced. (But... maybe that's not going to happen anytime soon? If not, we should remove it.) Also, I thought you had said that you might not be able to hide the button?  I don't have a strong opinion on this one, so defer to you, but was curious how it would look.

**Comment by mckoss** [comment]
I removed it.  It can come back very quickly as it's a build-option for the site.
