### ISSUE TITLE
Nav Bar: Enroll button 

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#86]
If it is possible to hide the Enroll button on the Nav bar, please do.

(If it is not possible, please let me know how many characters of space we have. I really don't think we should show this button in Nav Bar at all)

**Comment by mckoss** [comment]
I made all reference to enrollment conditional on a site parameter.  So, when we are ready, we can just change that variable and re-build the site.

Note that I also added a FAQ entry asking about the enrollment date.  It would be good to get a better statement there than my boilerplate.

@ashlchap

**Comment by ashlchap** [comment]
Ok that's fine. I'm opening a separate issue with tweaks to that FAQ. Thanks
