### ISSUE TITLE
Edit to the footer of website

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#88]
Please add an "s" to the FAQ link at the bottom of the website:

FAQs

**Comment by mckoss** [comment]
That doesn't look correct to me.  FAQ already stands for [Frequently Asked Questions](https://en.wikipedia.org/wiki/FAQ) - so adding the "s" implies their a multiple lists of questions and not just one list.

**Comment by ashlchap** [comment]
Yes, you are correct. Sorry, disregard.!
