### ISSUE TITLE
Nav bar design edit: Web page indicator

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#89]
Note: we got feedback that it wasn't clear from the Nav bar what page you're on when you're on the site. (i.e. when you're on the Partner page, the Partner heading in the Nav Bar doesn't stand out) We'd like to create something to indicate that in the Nav bar -- either that it stays bold when you're on that page, or it is underlined in red. See the Webflow website as the example:

https://reskill.webflow.io/partner

**Comment by mckoss** [comment]
The active page will be highlighted in the same way (red underline).
