### ISSUE TITLE
Partner page: design edit

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#94]
Under "Thank You!" please change the scroll bar with photos so that the first person starts from the left of the page, not the center, so that it runs all the way across the Partner page. (So that there are three people featured on the About Us page at once, not two)

**Comment by mckoss** [comment]
I can do that.  But, just so you know - the behavior of the carousel is to CENTER the active card.  So, I can start at the 2nd card in the list.  This will have the side-effect that the first card will be scrolled off the left for narrow screens (mobile).
