### ISSUE TITLE
News page- Design edits

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#96]
NOTE: We got feedback that people preferred the look and feel/design of the blog on the webflow page vs. the blog ("news") page on Github.  Mike created the News page to tie directly to the Youtube channel. Is it possible to keep this format but simply change the design of the News page so that it LOOKS a bit more like the Webflow page? 

For instance: larger font for the headlines, and perhaps bigger photos?

Here's the webflow  page:

https://reskill.webflow.io/blog

**Comment by AlexMNet** [comment]
Hi @ashlchap edits have been made and merged. Please let me know if any updated changes are needed!

**Comment by ashlchap** [comment]
Alex - this looks great, thank you! I have a new blog post to add with images, and would like to make one change to the Demo Day blog. I will post those as a separate issue for you to do. Thanks!

**Comment by AlexMNet** [comment]
@ashlchap thank you and sounds great!
